version: "3.8"
services:
  angular-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: sokhnadieng/angular-app:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - angular_net

networks:
  angular_net:
