name: CI/CD Angular → Docker → Docker Hub

on:
  push:
    branches:
      - main   # Se déclenche à chaque push sur main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances Angular
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Angular prod
      - name: Build Angular
        run: npm run build --prod

      # 5️⃣ Connexion à Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build et Push l'image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: sokhnadiba/angular-app:latest
